/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreditosImport } from './routes/creditos'
import { Route as CategoriasImport } from './routes/categorias'
import { Route as AutoresImport } from './routes/autores'
import { Route as AcercaImport } from './routes/acerca'
import { Route as IndexImport } from './routes/index'
import { Route as ConceptosIndexImport } from './routes/conceptos/index'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'
import { Route as ConceptosConceptIdImport } from './routes/conceptos/$conceptId'

// Create/Update Routes

const CreditosRoute = CreditosImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRoute,
} as any)

const CategoriasRoute = CategoriasImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRoute,
} as any)

const AutoresRoute = AutoresImport.update({
  id: '/autores',
  path: '/autores',
  getParentRoute: () => rootRoute,
} as any)

const AcercaRoute = AcercaImport.update({
  id: '/acerca',
  path: '/acerca',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ConceptosIndexRoute = ConceptosIndexImport.update({
  id: '/conceptos/',
  path: '/conceptos/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const ConceptosConceptIdRoute = ConceptosConceptIdImport.update({
  id: '/conceptos/$conceptId',
  path: '/conceptos/$conceptId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/acerca': {
      id: '/acerca'
      path: '/acerca'
      fullPath: '/acerca'
      preLoaderRoute: typeof AcercaImport
      parentRoute: typeof rootRoute
    }
    '/autores': {
      id: '/autores'
      path: '/autores'
      fullPath: '/autores'
      preLoaderRoute: typeof AutoresImport
      parentRoute: typeof rootRoute
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasImport
      parentRoute: typeof rootRoute
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosImport
      parentRoute: typeof rootRoute
    }
    '/conceptos/$conceptId': {
      id: '/conceptos/$conceptId'
      path: '/conceptos/$conceptId'
      fullPath: '/conceptos/$conceptId'
      preLoaderRoute: typeof ConceptosConceptIdImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/conceptos/': {
      id: '/conceptos/'
      path: '/conceptos'
      fullPath: '/conceptos'
      preLoaderRoute: typeof ConceptosIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/autores': typeof AutoresRoute
  '/categorias': typeof CategoriasRoute
  '/creditos': typeof CreditosRoute
  '/conceptos/$conceptId': typeof ConceptosConceptIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/conceptos': typeof ConceptosIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/autores': typeof AutoresRoute
  '/categorias': typeof CategoriasRoute
  '/creditos': typeof CreditosRoute
  '/conceptos/$conceptId': typeof ConceptosConceptIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/conceptos': typeof ConceptosIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/autores': typeof AutoresRoute
  '/categorias': typeof CategoriasRoute
  '/creditos': typeof CreditosRoute
  '/conceptos/$conceptId': typeof ConceptosConceptIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/conceptos/': typeof ConceptosIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca'
    | '/autores'
    | '/categorias'
    | '/creditos'
    | '/conceptos/$conceptId'
    | '/demo/tanstack-query'
    | '/conceptos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerca'
    | '/autores'
    | '/categorias'
    | '/creditos'
    | '/conceptos/$conceptId'
    | '/demo/tanstack-query'
    | '/conceptos'
  id:
    | '__root__'
    | '/'
    | '/acerca'
    | '/autores'
    | '/categorias'
    | '/creditos'
    | '/conceptos/$conceptId'
    | '/demo/tanstack-query'
    | '/conceptos/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcercaRoute: typeof AcercaRoute
  AutoresRoute: typeof AutoresRoute
  CategoriasRoute: typeof CategoriasRoute
  CreditosRoute: typeof CreditosRoute
  ConceptosConceptIdRoute: typeof ConceptosConceptIdRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ConceptosIndexRoute: typeof ConceptosIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcercaRoute: AcercaRoute,
  AutoresRoute: AutoresRoute,
  CategoriasRoute: CategoriasRoute,
  CreditosRoute: CreditosRoute,
  ConceptosConceptIdRoute: ConceptosConceptIdRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ConceptosIndexRoute: ConceptosIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/acerca",
        "/autores",
        "/categorias",
        "/creditos",
        "/conceptos/$conceptId",
        "/demo/tanstack-query",
        "/conceptos/"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/acerca": {
      "filePath": "acerca.tsx"
    },
    "/autores": {
      "filePath": "autores.tsx"
    },
    "/categorias": {
      "filePath": "categorias.tsx"
    },
    "/creditos": {
      "filePath": "creditos.tsx"
    },
    "/conceptos/$conceptId": {
      "filePath": "conceptos/$conceptId.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    },
    "/conceptos/": {
      "filePath": "conceptos/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
