/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreditosImport } from './routes/creditos'
import { Route as ConceptosImport } from './routes/conceptos'
import { Route as CategoriasImport } from './routes/categorias'
import { Route as AcercaImport } from './routes/acerca'
import { Route as IndexImport } from './routes/index'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'

// Create/Update Routes

const CreditosRoute = CreditosImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRoute,
} as any)

const ConceptosRoute = ConceptosImport.update({
  id: '/conceptos',
  path: '/conceptos',
  getParentRoute: () => rootRoute,
} as any)

const CategoriasRoute = CategoriasImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRoute,
} as any)

const AcercaRoute = AcercaImport.update({
  id: '/acerca',
  path: '/acerca',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/acerca': {
      id: '/acerca'
      path: '/acerca'
      fullPath: '/acerca'
      preLoaderRoute: typeof AcercaImport
      parentRoute: typeof rootRoute
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasImport
      parentRoute: typeof rootRoute
    }
    '/conceptos': {
      id: '/conceptos'
      path: '/conceptos'
      fullPath: '/conceptos'
      preLoaderRoute: typeof ConceptosImport
      parentRoute: typeof rootRoute
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/categorias': typeof CategoriasRoute
  '/conceptos': typeof ConceptosRoute
  '/creditos': typeof CreditosRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/categorias': typeof CategoriasRoute
  '/conceptos': typeof ConceptosRoute
  '/creditos': typeof CreditosRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/acerca': typeof AcercaRoute
  '/categorias': typeof CategoriasRoute
  '/conceptos': typeof ConceptosRoute
  '/creditos': typeof CreditosRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca'
    | '/categorias'
    | '/conceptos'
    | '/creditos'
    | '/demo/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerca'
    | '/categorias'
    | '/conceptos'
    | '/creditos'
    | '/demo/tanstack-query'
  id:
    | '__root__'
    | '/'
    | '/acerca'
    | '/categorias'
    | '/conceptos'
    | '/creditos'
    | '/demo/tanstack-query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcercaRoute: typeof AcercaRoute
  CategoriasRoute: typeof CategoriasRoute
  ConceptosRoute: typeof ConceptosRoute
  CreditosRoute: typeof CreditosRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcercaRoute: AcercaRoute,
  CategoriasRoute: CategoriasRoute,
  ConceptosRoute: ConceptosRoute,
  CreditosRoute: CreditosRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/acerca",
        "/categorias",
        "/conceptos",
        "/creditos",
        "/demo/tanstack-query"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/acerca": {
      "filePath": "acerca.tsx"
    },
    "/categorias": {
      "filePath": "categorias.tsx"
    },
    "/conceptos": {
      "filePath": "conceptos.tsx"
    },
    "/creditos": {
      "filePath": "creditos.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
